import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Form from '@/components/Form'

export default function Home() {
	return (
		<>
			<Head>
				<title>Basic Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.header}>
				<Image src='/google_logo.png' height={80} width={80} alt='Google G Icon' />
				<h1>oogle Sheets API</h1>
			</div>
			<Form />
		</>
	)
}
