import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Form from '@/components/Form'
import Packages from '@/components/Packages'
import Search from '@/components/Search'

export default function Home() {
	return (
		<div className={styles.wrapper}>
			<Head>
				<title>Basic Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.nav}>
				<Image src='/google_logo.png' height={80} width={80} alt='Google G Icon' />
				<h1>oogle Sheets API</h1>
			</div>
			<div className={styles.container}>
				<Form />
				<div className={styles.packagesSearchContainer}>
					<Packages />
					<Search />
				</div>
			</div>
		</div>
	)
}
